### PR TITLE
Feature new pagination bar (kill dots)

### PR DESCRIPTION
**Pull request by crdlc**
Hey,

```
I have just implemented the first version of the pagination bar. Basically, the pagination bar is based on the idea of horizontal scroll bar. You can see a screenshot of the prototype here
```

screencap

Regards

### CODE REVIEW

**Comment by ferjm** [comment]
Please, do not include commits in your pull request that are already merged in develop

**Comment by ferjm** [comment]
Merged. Please, check that everything is ok.

**Comment by crdlc** [comment]
hi, i know, i wrote you on the skype about this problem because i follow the instructions and i guess that i'm doing anything wrong

**Comment by crdlc** [comment]
I'm checking the develop branch and I think that the two last commits aren't merged

**Pull request closed without merging**
